spring:
  #  配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://192.168.231.131:26000/book?currentSchema=book
    url: jdbc:postgresql://113.44.151.111:26000/book?currentSchema=book
    username: tloy
    password: 20010521Yjc
    # password: SIsi0521